app/scripts/main.js
app/templates_versions/community/config.js
app/templates_versions/enterprise/config.js

* Login redirects to the dashboard's main page => if we share the link of an other subview and the user in not logged in, he be redirected to the login page. Once he is logged in, he will be redirected to the main page (and not the shared one)
* Checking if properties already set before calling getProperties()

 Login redirects to the given url

---

gradle.properties

The automation-dashboard in this branch now references subviews in the same branch

Sync the submodules branches

---

app/templates_versions/community/subviews.json
app/templates_versions/enterprise/subviews.json

Reverts ow2-proactive/automation-dashboard#200

Revert "Cloud watch contextual menu"

---

app/templates_versions/community/subviews.json
app/templates_versions/enterprise/subviews.json

Reverts ow2-proactive/automation-dashboard#201

Revert "Revert "Cloud watch contextual menu""

---

app/templates_versions/community/subviews.json
app/templates_versions/enterprise/subviews.json

(cherry picked from commit c7176ad)

Adding 'beta' next to Cloud Watch name in the menu

---

app/templates_versions/community/subviews.json
app/templates_versions/enterprise/subviews.json

Reverts ow2-proactive/automation-dashboard#222

Revert "Init function in job planner calendar view not needed"

---

app/templates_versions/community/subviews.json
app/templates_versions/enterprise/subviews.json

Reverts ow2-proactive/automation-dashboard#223

Revert "Revert "Init function in job planner calendar view not needed""

---

app/templates_versions/community/subviews.json
app/templates_versions/enterprise/subviews.json

New Order: 
(^) genericCatalog
(v) workflowAutomation
... rest doesn't change

Reorder Portals List in side menu bar

---

app/resources/config.json
app/scripts/main.js
app/templates_versions/common/index.html
app/templates_versions/common/navigation.html
app/templates_versions/community/subviews.json
app/templates_versions/enterprise/subviews.json
app/views/common/topnavbar.html
package.json

In this PR, we add a service (along with corresponding url in config) and a controller to job-analytics portal.
We also add a few libraries needed in job-analytics portal
We adapt the navbar styling to the job-analytics-portal as well

Add job-analytics api service

---

app/templates_versions/common/index.html
app/templates_versions/community/subviews.json
app/templates_versions/enterprise/subviews.json
bower.json
package.json

In this PR, we add the dependencies and new files required in the second deliverable of Job Analytics
We also do some cleaning

Add dependencies for second shot of Job Analytics

---

app/styles/dashboard-style.css
app/templates_versions/common/navigation.html
app/views/common/topnavbar.html

Update navigation header to sync with other portals headers

---

app/templates_versions/common/index.html
app/templates_versions/community/subviews.json
app/templates_versions/enterprise/subviews.json
bower.json
package.json

In this PR we add some html templates as dependencies to Job Analytics Portal

Add new templates to ui-grid

---

app/templates_versions/common/index.html
app/templates_versions/community/subviews.json
app/templates_versions/enterprise/subviews.json

First version of node gantt view

add node-gantt view

---

app/scripts/main.js
app/templates_versions/common/index.html
app/templates_versions/common/navigation.html
app/templates_versions/community/subviews.json
app/templates_versions/enterprise/subviews.json

In this PR, we apply the required changes to include the new notifications portal

Add new notifications portal

---

app/templates_versions/community/subviews.json
app/templates_versions/enterprise/subviews.json

Add related files declaration to enable the catalog-portal to add a button (with key icon) to show a modal for managing third-party credentials when submit a workflow with PA:CREDENTIAL variables.

Add files for catalog-portal 3rd-party-credentials modal

---

app/templates_versions/community/subviews.json
app/templates_versions/enterprise/subviews.json

No changes in code, just split big files into dedicated controller files and grouped some other code snippets in dedicated services

Refactor WFA by splitting and grouping code in multiple files

---

Gruntfile.js
app/scripts/main.js

In this PR, 
- we implement the control of portals access permission for automation-dashboard
- adapt portal links on the left side navbar

Portals access permission for automation-dashboard

---

Gruntfile.js
app/scripts/main.js

Fix notifications count on navigation menu

---

app/scripts/directives.js
app/styles/dashboard-style.css
app/templates_versions/common/index.html
package.json

- Create new directive for back-to-top browsing button (minimized and modified version from an independent library)
- Add dependency for ng-infinite-scroll

Add back-to-top directive and new dependency for infinite-scroll

---

app/styles/dashboard-style.css
app/templates_versions/community/subviews.json
app/templates_versions/enterprise/subviews.json
app/views/common/topnavbar.html

- Add notification-portal html templates and remove notifs btn next to logout btn

Add notification-portal html templates and remove notifs btn next to logout btn

---

app/scripts/modals/file-browser-modal-controller.js
app/views/modals/dataspace-file-browser.html

- Add description of global/user dataspace in the dataspace file browser
- Change 'Cancel' button text to 'Close' when the file browser is not opened for a specific variable.

improve file browser modal description and close button

---

app/scripts/utils.js

- remove expired variable model: PA:OPTIONAL_GLOBAL_FILE and PA:OPTIONAL_USER_FILE
- add an utils function to handle the `null` or `undefined` variable value.

remove expired variable model OPTIONAL_XX_FILE

---

app/styles/dashboard-style.css
app/views/common/topnavbar.html

Relocate custom brand logo to the left of AD shortcut

---

app/views/common/topnavbar.html

Update custom brand logo layout and link

---

app/scripts/utils.js

to create a String composed by translated and non translated strings.

Add util translation method

---

app/templates_versions/community/subviews.json
app/templates_versions/enterprise/subviews.json

(This PR doesn't remove WA yet, it just copies the remaining modals from WA to WE)

Copy logs & resultmap modals to WE

---

build.gradle

Upgrade nodejs version from 4.4.4 to 14.16.0 to fix compilation issues of dependency libraires using unsupported JS syntax by nodes v4

Upgrade nodejs version from 4.4.4 to 14.16.0

---

app/scripts/directives.js
app/styles/dashboard-style.css

Add Directive showDropdownFromTemplate to fix uib-dropdown position issues when loaded from templates & appended-to-body

---

app/templates_versions/community/subviews.json
app/templates_versions/enterprise/subviews.json

Add secondary HTML file declaration for WE

Add result map HTML dependency for WE

---

app/scripts/directives.js
app/templates_versions/common/index.html
package.json

- Add angular-virtual-scroll dependency 
- Remove waiting cursor effect while loading dropdown because of an unexpected occasional behavior

Add angular-virtual-scroll dependency

---

app/scripts/utils.js
app/styles/dashboard-style.css
app/views/modals/dataspace-file-browser.html

- Add progress-bar effect to upload dropdown
- Improve dropdown css & override old inspire colors
- improve indentations for old code

Add progress-bar effect to upload dropdown

---

app/styles/dashboard-style.css

Make disabled dropdown menu items look disabled (use a clearer gray)

Improve disabled dropdown text color

---

app/scripts/inspinia.js
app/styles/dashboard-style.css
app/templates_versions/common/index.html
package.json

- Add JS panel resizing library
- FIX page height issues: use CSS for page height instead of JS

Add panel resizing library & 

---

app/scripts/modals/catalog-objects-modal-controller.js
app/styles/dashboard-style.css
app/views/common/workflow-variables.html
app/views/modals/catalog_objects_modal.html

This PR aims to:
- remove the unnecessary "show all" checkbox aside buckets
- add the search bar (search by catalog object name) to have a unified UI of catalog modal as in studio

remove show all checkbox for PA:CATALOG var modal

---

app/scripts/modals/file-browser-modal-controller.js
app/views/modals/dataspace-file-browser.html

- add form instead of ng-keyup and ng-click
- change the height of the Search button

refactor-filter-dataSpace-file-browser

---

app/scripts/main.js

- replace modal notifications with pop-up notifications 
- stop button loading forever

Replace modal notifications by pop-up notifications in JP 

---

app/scripts/main.js
app/styles/dashboard-style.css

- fix the delay in hiding the spinner in 'confirm association' button
- remove vertical scroll on the pop up of success create association

JP::create association 

---

app/scripts/modals/catalog-objects-modal-controller.js
app/views/modals/catalog_objects_modal.html

fix synch requests when we switsh between the buckets

Issue on sub-workflows selection in WE

---

app/scripts/main.js

Pass Job data to the context menu scope before it is displayed

WE: Support the display of a context-menu when a user right clicks on a job row

---

app/styles/dashboard-style.css
app/views/common/workflow-variables.html

Update variables display in submission modal

---

app/scripts/catalog-view-controller.js
app/scripts/main.js
app/scripts/submission-window-controller.js
app/templates_versions/common/config.js
app/views/common/catalog-view.html

1. Using Joker in the URL
2. Fix sessionid issue

Submission of a Wf. from a specific URL

---

app/scripts/language-controller.js
app/scripts/main.js
app/scripts/variables-controller.js
app/templates_versions/common/index.html
app/views/common/language-dropdown.html
app/views/common/submission-window-view.html
app/views/common/topnavbar.html

- in the detachable window, when resubmitting a job from the detachable window, show a notification same as described in point 1 but this time from the detachable window.
- display a notification for other operations (like kill and remove and maybe others to check) in detachable window.
- Apply the same language switch menu on submission window

Add selected language in the externals window and some improvements

---

app/scripts/modals/third-party-credential-modal-controller.js

Also move reset of text area size in finally block as it must be executed even if request fails

Manage credentials: Reset value input to be hidden after creation

---

build.gradle

This change seem to prevent automation-dashboard build issues

Test using http for dotrc mirror

---

app/scripts/main.js
app/templates_versions/community/subviews.json
app/templates_versions/enterprise/subviews.json

Notification on Execution Time: too short or too long / average
