- app/scripts/main.js
- app/templates_versions/community/config.js
- app/templates_versions/enterprise/config.js
The fetch of the properties wasn't chained properly to the login, so the login code could execute before the client even get the properties like the url to log into. My fix forces login code to execute only once the getProperties has finished executing.
> Fix login problem

- app/templates_versions/enterprise/config.js
Removing the console.log message displaying in the enterprise version whenever there's a isSessionValide call.
> Remove debug log

- app/templates_versions/common/index.html
Using minified libraries makes the build faster, but only 2 seconds so it isn't worth merging into master. That's why I created a branch. 
Some libraries don't have minified versions (like code mirror) and I noticed that for others it makes the build longer (angular gantt).
> Use minified library files for faster build

- app/templates_versions/common/index.html
- bower.json
In this PR, we add the angular-ui-sortable (jquery-ui wrapper) to be used in Job Analytics
> Add ui-sortable dependency for Job Analytics

- bower.json
Some dependencies require a recent version of angular-bootstrap
This PR updates its version to the latest.
Tested for compilation compatibility and has no apparent regression.
> Update Angular Bootstrap version to latest

- app/styles/dashboard-style.css
- app/templates_versions/common/index.html
- app/templates_versions/common/navigation.html
- app/templates_versions/community/subviews.json
- app/templates_versions/enterprise/subviews.json
- app/views/common/content.html
- app/views/common/topnavbar.html
- package.json
In this PR we:
- Add a documentation link at the bottom of the left sidebar.
- Apply a corporate-orange background to Automation-Dashboard button at the top nabber
- Update the false corporate-orange color used everywhere with the *true* corporate-orange #E86D1F
- Add a dependency script for Job Analytics Portal
- Remove unused dependencies from Job Analytics
> Add doc link to sidebar, update styles and add JA dependencies

- app/scripts/modals/third-party-credential-modal-controller.js
- app/styles/dashboard-style.css
- app/templates_versions/common/index.html
- app/templates_versions/community/subviews.json
- app/templates_versions/enterprise/subviews.json
- app/views/modals/third_party_credentials.html
Moving the third-party-credentials management modal from generic-catalog-portal to the automation-dashboard, so that it can easily reused in different subviews (e.g., catalog-portal, workflow-automation, cloud-automation, calendar-associations).
> feat: Add third-party-credentials modal

- app/scripts/modals/file-browser-modal-controller.js
- Fix the bug that in firefox, file browser modal create new folder can't input.
- Fix the new folder icon.
- Improve new folder input: add auto focus and select all text.
> fix: file browser modal new folder

- app/scripts/modals/file-browser-modal-controller.js
Currently, having a file/folder name containing colons will cause a vfs bug when browsing files.
This PR is to do a temporary workaround for this bug: disallow colon in uploaded file and created folder in front-end.
> file browser disallow colon in uploaded file and created folder

- app/scripts/utils.js
Fix the bug when check whether a variable needs special UI (i.e., it's not simply showing its value with an inputbox, for example, the variables with the model 'pa:boolean', 'pa:list', or 'pa:datetime' etc) during workflow submission, the variable model may only contain the specific model keyword instead of exactly the same.
For example, a list variable may be defined as `PA:LIST(a,b,c)` instead of `PA:LIST`. The previous commits in the subviews introduce the bug: 
- https://bitbucket.org/activeeon/generic-catalog-portal/pull-requests/146/improve-file-browser-modal/diff
- https://bitbucket.org/activeeon/job-planner-portal/pull-requests/266/improve-file-browser-modal/diff
- https://bitbucket.org/activeeon/cloud-automation/pull-requests/250/improve-file-browser-modal/diff
> fix: add utils func to check if a variable needs special UI

- app/scripts/utils.js
When opening endpoints from a local installation, no protocol is added to 'localhost'.
This PR fixes this scenario by adding the actual protocol detected by the browser to the endpoint link (otherwise, it wouldn't work)
> Fix service endpoint links without protocol

- app/styles/dashboard-style.css
- app/templates_versions/community/subviews.json
- app/templates_versions/enterprise/subviews.json
- Use templates for dropdowns to avoid adding them to the Dom (a dropdown by job !). From now on, they will be loaded on-demand (on-click) and removed from the Dom as soon as they are closed. This represents a big performance improvement because it cuts by a 1/3rd the number of angularjs watchers.
> Add HTML templates for WE dropdowns

- app/scripts/modals/file-browser-modal-controller.js
- app/scripts/utils.js
- Change to token authentication to use browser download for dataspace file download;
- Reverse the upload progress bar (width as complete percentage instead of remaining percentage);
- Create new notification object for success / error instead of reusing the uploading notification to avoid the user has manually closed the uploading notification.
> Improve dataspace file download using token and reverse upload progress bar

- app/scripts/directives.js
- Add a wait until (retry until) a dropdown from an html template is fully added to the dom.
- This works only for dropdown that use the `showDropdownFromTemplate` custom-made directive
> Fix dropdown loading directive for slow networks

- app/resources/locales/locale-en.json
- app/resources/locales/locale-es.json
- app/resources/locales/locale-fr.json
- app/resources/locales/locale-pt.json
- app/scripts/main.js
- app/scripts/modals/file-browser-modal-controller.js
- app/scripts/utils.js
- app/views/modals/dataspace-file-browser.html
- app/views/modals/uploading-files-dropdown.html
- Clean uploading files when closeSession to avoid security issue of exposing uploading files to unauthenticated user; 
- Identify the uploading files is global/user space file; 
- Add confirmation for cancel uploading; 
- Remove annoying error message for canceled upload; 
- The total remain time of uploading files should base on max instead of sum of all uploads remain time;
- Add close button for the toastr notification ; 
- Add tooltips for show hidden; 
- Enable ESC key to close file browser modal; 
- Add space before dropdown triangle.
> Improve uploading files dropdown

- app/resources/locales/locale-en.json
- app/resources/locales/locale-es.json
- app/resources/locales/locale-fr.json
- app/resources/locales/locale-pt.json
- app/scripts/modals/third-party-credential-modal-controller.js
- app/views/modals/third_party_credentials.html
In the modal of managing 3rd-party-credentials when submitting a workflow with PA:CREDENTIAL variables, add a checkbox "Multiline credential" to allow the user to input the multi-lines credential value by switching between the password input (for single line credential) and textarea (for multi-lines credential).
> Support to add multi-lines credential value in 3rd-party-credential modal

- app/scripts/directives.js
- app/scripts/modals/file-browser-modal-controller.js
- app/templates_versions/common/app.js
- app/templates_versions/common/config.js
- app/views/modals/dataspace-file-browser.html
The file uploading feature is recently broken because now the debug info is disabled (https://github.com/ow2-proactive/automation-dashboard/blob/master/app/templates_versions/common/app.js#L44), so the input #selected-upload-file can no longer access the scope with the current way. 
ref: https://github.com/angular/angular.js/issues/9515
This PR aims to fix this problem by creating a custom directive `input-file-change` to pass the scope without debug info.
> fix the bug of uploading files in the debug info disabled environment.

- build.gradle
jar was probably removed by one of the node or grunt tasks. To fix this, force building the jar just before doing the install task.
> To cherry-pick : fix gradle install

- app/scripts/main.js
Move ui-grid import declaration to the main controller to make it available in both JA and catalog.
This is the only way to import ui-grid without making it conflict with itself if imported separately in different sub-portals.
> Move ui-grid import to main controller

- app/scripts/main.js
After logging out, AD did not send the disconnect request in order to invalidate the sesssionId like the other portals do. 
When logging out, AD just removed “pa.session“ from the local storage. 
So when the user logs out from AD, scheduler and RM can continue to send requests with the same sessionId because it is valid.
Studio portal logs out because it verifies if the “pa.session“ is removed.
> disconnect-user-when-logging-out

- app/scripts/main.js
- app/views/common/topnavbar.html
- app/views/modals/change_logo_modal.html
Changes the customer logo in the navbar
> Add update logo menu item for admins in Help menu of the navbar
